ports:
    - port: 3000
      onOpen: open-browser
tasks:
    - init: >
        npm i vercel -g &&
        npm install &&
        cp .env.example .env
      command: >
        npm i vercel -g

vscode:
  extensions:
    - dsznajder.es7-react-js-snippets@3.1.1:debf39b2c860197045844163048ca4dd